### ISSUE TITLE
blt tests returns error "tests:deprecated" is not defined

### ISSUE THREAD

**Issue by nmillin** [acquia/blt-drupal-check#3]
Hi,
I am trying to get acquia pipelines working with blt-drupal-check, but I'm running into an issue with the blt tests command. I believe somewhere in Acquia BLT, the blt tests command is calling tests:deprecated when it shouldn't. This is resulting in an error that causes the command to error out.

**Example from Acquia Pipelines**
Executing step tests.
+ source ${BLT_DIR}/scripts/pipelines/tests
export PATH=${COMPOSER_BIN}:${PATH}
blt tests --define drush.alias='${drush.aliases.ci}' -D behat.web-driver=chrome --no-interaction --ansi --verbose
.
..
...
> tests:frontend

[info] Skipped frontend-test target hook. No hook is defined.

[error]  Command "tests:deprecated" is not defined.

Did you mean one of these?
    tests
    tests:deprecated:modules
    tests:deprecated:themes
    tests:frontend
    tests:frontend:run
    tests:security-composer
    tests:security-drupal
    tests:server:kill
    tests:server:start 

1.413s total time elapsed.
pipelines_kill_background_processes
pstree -p $$  grep -E -o '([0-9]+)'  grep -v "^$$\$"  sort -k2 -rn

I was able to get around this issue by updating DrupalCheckCommand.php to @command tests:deprecatedmodules & @command tests:deprecatedthemes. Now the blt tests command doesn't try to run the command "tests:decrecated".

I'll try to attach a patch/PR showing this.

Please let me know if you have any questions. Thanks.

-Nate

**Comment by danepowell** [comment]
BLT expects every "namespace" (such as "tests") to have a set of top-level commands:
- https://github.com/acquia/blt/blob/main/src/Robo/Commands/Tests/TestsAllCommand.php
- https://github.com/acquia/blt/blob/42f497f7c4aa8e1f484804a0435a6d0d80b18407/src/Robo/BltTasks.php#L114

In this case, the top-level command for this plugin would be `tests:deprecated`. Thus, I think a better solution would be to add a default `tests:deprecated` command that runs all deprecation tests.

**Comment by nmillin** [comment]
@danepowell sounds good to me. 

I've updated https://github.com/acquia/blt-drupal-check/pull/4/files to include the tests:deprecated command. Let me know what you think and if there should be changes. Thanks.
