### ISSUE TITLE
Composer Update for mglaman/drupal-check

### ISSUE THREAD

**Issue by nmillin** [acquia/blt-drupal-check#5]
# Background
https://github.com/mglaman/drupal-check/issues/233 introduced an update for an error:

`Parameter excludes_analyse has been deprecated so use excludePaths only from now on.`

and there is now a new release of https://github.com/mglaman/drupal-check/releases/tag/1.1.10.

This is causing our acquia-pipelines.yml to fail because we have the following in our acquia-pipelines.yml file.
`        - tests:
            type: script
            script:
              - source ${BLT_DIR}/scripts/pipelines/tests`

In the composer.json of this project, this new version isn't allowed:
`"mglaman/drupal-check": ">=1.0.10 <1.1.0 || 1.1.1",`

# Idea to address this
Update the composer.json to:
`"mglaman/drupal-check": ">=1.0.10 <1.1.0 || 1.1.*",` **or**  `"mglaman/drupal-check": "^1.1",`. I'm not sure why the drupal-check versions are so defined. 

Update dependencies

**Comment by UTCGilligan** [comment]
@nmillin are you going to PR your proposed solution? Have you tested it as a patch?

**Comment by nmillin** [comment]
@UTCGilligan eventually I'll create a PR, but I'm a bit slammed currently (in work and life). Might be a while before I get to this. 
I posted this to help others and maybe someone else could do the PR :)

**Comment by UTCGilligan** [comment]
@nmillin This seems to have "fixed itself", or at least Composer is no longer complaining about the constraint in my latest attempts to `require --dev` this plugin package.

**Comment by UTCGilligan** [comment]
Now this is causing problems with:
- phpstan 'bootstrapFiles' config option instead of deprecated 'bootstrap'
- https://github.com/mglaman/drupal-check/issues/178
- https://github.com/mglaman/drupal-check/pull/179

**Comment by nmillin** [comment]
PR #6 so closing issue. Hopefully this helps you too @UTCGilligan

**Comment by nmillin** [comment]
Note for future Nate. https://packagist.org/packages/acquia/blt-drupal-check needed to be manually updated by clicking on the "update now" link.
